# We use the slim image (Debian-based) to avoid compatibility issues.
FROM node:18-slim

# Create the workdir in the container
WORKDIR /app

#1. Copy the package file created manually.
COPY package.json ./

# 2. Now Docker has the file and can download the libraries inside the container.
RUN npm install

# 3. Copy the rest (server.js, index.html, etc.)
COPY . .

# Let's expose the door
EXPOSE 3000

# Start
CMD ["node", "server.js"]